config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes, only: [:index, :show]

  root to: 'recipes#index'
end

app/models/chef.rb
class Chef < ContentfulModel::Base
  self.content_type_id = 'chef'
end

app/models/recipe.rb
class Recipe < ContentfulModel::Base
  self.content_type_id = 'recipe'

  has_one :chef
  has_many :tags
end

app/models/tag.rb
class Tag < ContentfulModel::Base
  self.content_type_id = 'tag'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def process_action(*args)
    super
  rescue Contentful::BadRequest => exception
    render 'error/contentful_error', status: 503
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  PER_PAGE = 20

  def index
    @recipes = RecipesDecorator.decorate(
      Recipe.paginate(page, PER_PAGE, ['fields.title', 'sys.id']).load
    )
  end

  def show
    @recipe = RecipeDecorator.decorate(Recipe.find(params[:id]))
  end

  private

  def page
    (params[:page] || 1).to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Recipes
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    .navbar.navbar-dark
      = link_to t('.recipes'), root_path, class: 'navbar-brand'
    .container
      = yield

app/views/recipes/index.html.haml
%table.table.table-dark.recipes
  %thead
    %th
    %th= t('.title')

  %tbody
    - @recipes.each do |recipe|
      %tr
        %td= image_tag(recipe.photo.url(width: 100))
        %td= link_to recipe.title, recipe_path(recipe.id)

- unless @recipes.first_page?
  = link_to t('.prev'), recipes_path(page: @recipes.page - 1)
- unless @recipes.last_page?
  = link_to t('.next'), recipes_path(page: @recipes.page + 1)

app/views/recipes/show.html.haml
.back= link_to t('.back'), root_path

.recipe
  .title= @recipe.title
  - if @recipe.chef.present?
    .chef= t('.chef', name: @recipe.chef.name)

  .photo
    = image_tag @recipe.photo.url

  .description= @recipe.description
  - if @recipe.tags.present?
    .tags= @recipe.tags_list